"""
Generate a U.S. Standard Atmosphere 1976 reference table (0-86 km) as CSV.

This is a convenience artifact so the standard-atmosphere values are available
to spreadsheets / MATLAB without running Python. The numbers come straight from
nearspace.atmosphere and reproduce the official USSA-1976 tables.

Run:  python3 generate_atmosphere_table.py
"""
import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from nearspace import atmosphere as atm

OUT = os.path.join(os.path.dirname(__file__), "us_standard_atmosphere_1976.csv")


def main():
    lines = ["# U.S. Standard Atmosphere 1976, generated by nearspace.atmosphere",
             "# Source: NOAA-S/T 76-1562 (NOAA/NASA/USAF), 1976.",
             "altitude_km,temperature_K,pressure_Pa,density_kgm3,speed_of_sound_mps"]
    for zk in range(0, 87):
        z = zk * 1000.0
        try:
            s = atm.atmosphere(z)
        except ValueError:
            continue
        lines.append(f"{zk},{s.temperature_K:.3f},{s.pressure_Pa:.5f},"
                     f"{s.density_kgm3:.6e},{s.speed_of_sound_mps:.3f}")
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(lines)-3} altitude rows)")


if __name__ == "__main__":
    main()
